services:
  webapp:
    build:
      context: .
      dockerfile: SecureNotes.Web/Dockerfile
    environment:
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certs/webapp.pfx 
      - ASPNETCORE_Kestrel__Certificates__Default__Password=SecureNotes_228
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=SecureNotesDb;User Id=sa;Password=SecureNotes_228;TrustServerCertificate=True
      - DOCKER_NETWORK_SUBNET=172.20.0.0/16
    volumes:
      - keys:/app/keys
      - ./certs/webapp.pfx:/app/certs/webapp.pfx:ro
      - ./certs/ca.crt:/app/certs/ca.crt:ro
    networks:
      - secure-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SecureNotes_228
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - secure-network

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/webapp.crt:/etc/nginx/ssl/webapp.crt:ro
      - ./certs/webapp.key:/etc/nginx/ssl/webapp.key:ro
      - ./certs/ca.crt:/etc/nginx/ssl/ca.crt:ro
    depends_on:
      - webapp
    networks:
      - secure-network

networks:
  secure-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  keys:
  sqldata: