services:
  webapp:
    build:
      context: .
      dockerfile: SecureNotes.Web/Dockerfile
    environment:
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certs/webapp.chained.crt
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/app/certs/webapp.key
      - ConnectionStrings__DefaultConnection=Server=db;Database=SecureNotesDb;User Id=sa;Password=SecureNotes_228;TrustServerCertificate=True
      - NGINX_IP_ADDRESS=172.20.0.12
    volumes:
      - keys:/app/keys:rw
      - ./certs/webapp.chained.crt:/app/certs/webapp.chained.crt:ro
      - ./certs/webapp.key:/app/certs/webapp.key:ro
    networks:
      secure-network:
        ipv4_address: 172.20.0.10

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SecureNotes_228
      - MSSQL_PID=Express
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      secure-network:
        ipv4_address: 172.20.0.11

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/webapp.chained.crt:/etc/nginx/ssl/webapp.chained.crt:ro
      - ./certs/webapp.key:/etc/nginx/ssl/webapp.key:ro
    depends_on:
      - webapp
    networks:
      secure-network:
        ipv4_address: 172.20.0.12

networks:
  secure-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  keys:
  sqldata: